name: continuous-integration

run-name: Running tests on '${{ github.head_ref || github.ref_name }}' by @${{ github.actor }}

on: pull_request

env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running tests in branch ${{ github.head_ref || github.ref_name }} triggered by @${{ github.actor }}"

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: graalvm
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: ./gradlew test

      - name: Verify
        run: ./gradlew check
